modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="power"
version="1.0.0.28.260620241435"
displayName="Keepers of the Stones II"
updateJSONURL="https://raw.githubusercontent.com/Environment-Studios-Official/Environment-Update-Center/main/kots_update_checker_fg.json"
displayURL="https://modrinth.com/mod/keepers-of-the-stones-2"
logoFile="logo.png"
credits="Created by Environment Studios"
authors="MagicalAlexey, Spinoraptor, Linnett, Cucuber, Samuelchik, Max_Di and many others"
description="Keepers of the Stones II is a mod created as a continuation of the original version of the Keepers of the Stones mod. It adds 48 new elemental stones that can be used to improve the character's skills and powers."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.power]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.power]]
    modId="kleiders_custom_renderer"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.power]]
    modId="geckolib"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.power]]
    modId="particlepresets"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.power]]
    modId="kleidersplayerrenderer"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.power]]
    modId="bettercombat"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.power]]
    modId="patchouli"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.power]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.power]]
    modId="playeranimator"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.power]]
    modId="particlepresets"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.power]]
    modId="cloth-config"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

