# Automatically builds and publishes the mod when a new release is created on GitHub.
# It uploads the mod to GitHub, CurseForge and Modrinth.

name: Beta

on:
  push:
    branches:
      - "1.20.1-beta"
env:                                              
  MINECRAFT_VERSION: 1.20.1                       
  JAVA_VERSION: 17      
  VERSION: 1.0.0.43
  RELEASE_NAME: Keepers of the Stones II 1.0.0.43 Beta

jobs:
  build:
    runs-on: ubuntu-latest                        
    steps:                                        
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Publish mod to CurseForge and Modrinth
        id: publish
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 906406
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          modrinth-id: hKbKT6ME
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          
          name: "${{env.RELEASE_NAME}}"                             
          version: "${{env.VERSION}}"
          version-type: beta
          changelog-file: BETA_CHANGELOG.md                                      

          loaders: |
            forge
            neoforge
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"
          dependencies: |
            required-dependency
            optional-dependency@0.1.0(optional)
            recommended-dependency@0.2.0(recommended)
            embedded-dependency@0.3.0(embedded)
            conflicting-dependency(conflicting)
            incompatible-dependency(incompatible)
            geckolib(required){modrinth:8BmcQJ2H}{curseforge:388172}#(ignore:github)
            playeranimator(required){modrinth:gedNE4y2}{curseforge:658587}#(ignore:github)
            pehkui(required){modrinth:t5W7Jfwy}{curseforge:319596}#(ignore:github)
            better-combat(recommended){modrinth:8BmcQJ2H}{curseforge:639842}#(ignore:github)
            epic-fight(incompatible){modrinth:vu3NZ5Ma}{curseforge:405076}#(ignore:github)
          modrinth-featured: false
          fail-mode: warn